# Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/workflows/blank.yml
# This action labels and assigns newly opened issues

name: Issue triager
on:
  issues:
    types: [opened]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - if: always()
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let isAnnouncement = false;
          const issueLabels = github.issues.listLabelsOnIssue({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          console.log(issueLabels);
          
          if (issueLabels && issueLabels.length) {
            const labelNames = issueLabels.map(label => label.name);
            
            console.log(labelNames);  
            isAnnouncement = labelNames.includes('announcement');
          }          
          
          if (!isAnnouncement) {
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs triage']
            })
          }        
