# Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/workflows/blank.yml
# This action labels and assigns newly opened issues

name: Issue triager
on:
  issues:
    types: [opened]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - if: always()
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueLabels = await github.issues.listLabelsOnIssue({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo
          });

          const issue = context.payload.issue;
          console.log(issue.title);

          if (issue.title.contains('[tool name]') && issue.body.contains('Tool name: <!--- Name -->')) {
            // Close the issue
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              state: 'closed'
            });

            // Comment on the issue
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: "This issue appears to have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!"
            });

            return;
          }

          const isAnnouncement = issueLabels.data && issueLabels.data
            .map(label => label.name)
            .includes('Announcement'); 
          
          if (!isAnnouncement) {
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs triage']
            })
          }       
