# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Test2
        shell: pwsh
        run: |
          Invoke-WebRequest -OutFile cuda_installer.exe -Uri https://developer.download.nvidia.com/compute/cuda/11.6.0/network_installers/cuda_11.6.0_windows_network.exe
          $process = Start-Process -FilePath $filePath -ArgumentList $ArgumentList -Wait -PassThru
          $exitCode = $process.ExitCode
          if ($exitCode -eq 0)
          {
            Write-Host "Windows Nvidia drivers are installed successfully"
            nvidia-smi
          }
          else
          {
            Write-Host "Windows Nvidia drivers installation failed. Non zero exit code returned by the installation process: $exitCode"
            exit $exitCode
          }
