# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Test1
        run: |
          brew install swig
      - name: Test2
        shell: pwsh
        run: |
          function Run-Command {
              param (
                  [Parameter(Mandatory=$true)]
                  [string] $Command,
                  [switch] $SuppressStderr
              )
              # Bash trick to suppress and show error output because some commands write to stderr (for example, "python --version")
              $redirectOutputArguments = If ($SuppressStderr) { "2> /dev/null" } Else { "2>&1" }
              $stdout = & bash -c "${Command} ${redirectOutputArguments}"

              return $stdout
          }

          function Take-Part {
              param (
                  [Parameter(ValueFromPipeline)]
                  [string] $toolOutput,
                  [string] $Delimiter = " ",
                  [int[]] $Part
              )
              $parts = $toolOutput.Split($Delimiter, [System.StringSplitOptions]::RemoveEmptyEntries)
              $selectedParts = $parts[$Part]
              return [string]::Join($Delimiter, $selectedParts)
          }
          
          Run-Command "swig -version" | Take-Part -Part 3
