on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-powershell:latest
    steps:
      - name: Azure
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-Module -Name Az -ListAvailable
          azPSVersion: "latest"
