on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          if (-not (Get-Module -Name Az -ListAvailable))
          {
            Write-Host "Installing Az module. This may take a few minutes..."
            Install-Module -Name Az -Scope CurrentUser -AllowClobber -Force -SkipPublisherCheck
          }
          
          Remove-AzResourceGroup -Name "RG" -Force
        shell: pwsh
