on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
           inlineScript: |
                  Remove-AzResourceGroup -Name "RG" -Force
           azPSVersion: "latest"
