on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: make project
        run: |
          mkdir my-project
          cd my-project
          yarn init --yes
          yarn add --dev gulp
          yarn gulp --version
      - name: create gulpfile
        run: |
          cd my-project
          echo "function defaultTask(cb) { setTimeout(() => { console.log('Delayed for 10 second.'); }, '10000'); cb(); } exports.default = defaultTask" > gulpfile.js
          yarn gulp
          echo something
          exit 0
