on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Azure
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-Module -Name Az -ListAvailable
          azPSVersion: "latest"
      - run: az version
        name: Az check
