on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-powershell:latest
    steps:
      - run: Get-Module -Name Az -ListAvailable
        shell: pwsh
